default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: Haophasop123
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: verdurao_rails_development

test:
  <<: *default
  database: verdurao_rails_test

production:
  primary: &primary_production
    <<: *default
    database: verdurao_rails_production
    username: verdurao_rails
    password: <%= ENV["VERDURAO_RAILS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: verdurao_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: verdurao_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: verdurao_rails_production_cable
    migrations_paths: db/cable_migrate
